
# Development Profile
spring:
  profiles: "dev"
  main:
    banner-mode: "off"
  application:
    name: "KafkaSpringProcessor"
    version: "1.0.0.0"
  kafka:
    bootstrap-servers: "localhost:9092"
    streams:
      application-id: "spring-kafka-processor"
      input-topic: "words-input"
      output-topic: "words-count"
  schedule:
    delay: "5000"
---


